use err::Result;

mod err;

fn main() -> Result<()> {
    println!("Hello, world!");

    Ok(())
}
